//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by good.rc
//
#define ID_SPRITEEDIT_FRAMETIME         104
#define IDC_POINTER                     104
#define ID_SPRITEEDIT_FRAMETIMEADD      105
#define IDR_MAINFRAME                   128
#define IDS_HELP_ADDGRIDLINE            129
#define IDD_NEWMAP                      201
#define IDR_TB_MAPEDIT                  207
#define IDB_BKBRUSH                     210
#define IDD_MAPPROP_GRID                211
#define IDD_NEWSPRITE                   219
#define IDR_TB_SPRITETILESET            220
#define IDR_TB_SPRITEEDIT               222
#define IDR_TB_SPRITEPREVIEW            224
#define IDR_TB_LEVELEDIT                227
#define IDD_ADDNEWLEVELITEM             229
#define IDD_PROPVIEW                    234
#define IDB_BITMAP1                     235
#define IDD_CHOICESPRITE                238
#define IDR_MENU_SNAP                   240
#define IDI_ICON1                       241
#define IDD_CHOICETEXTURE               241
#define IDD_CHOICEMAP                   242
#define IDR_TB_OUTPUT                   242
#define IDR_THEPLAYER1                  246
#define IDR_TB_STGESCRIPT               251
#define IDD_SNAPCUSTOMIZE               254
#define IDD_NEWPROJ                     255
#define IDD_SELTEXDIM                   257
#define IDD_GOTOVIEW                    258
#define IDB_BITMAP2                     262
#define IDB_OBJSTATE                    262
#define IDB_LVLOBJ                      263
#define IDR_MENU_LINE                   264
#define IDD_CHOICELVLOBJ                265
#define IDC_EDIT1                       1000
#define IDC_EDIT2                       1001
#define IDC_LIST1                       1001
#define IDC_EDIT3                       1002
#define IDC_EDIT4                       1003
#define IDC_EDIT5                       1004
#define IDC_BUTTON1                     1005
#define IDC_EDIT7                       1005
#define IDC_BUTTON2                     1006
#define IDC_CHECK1                      1007
#define IDC_EDIT6                       1008
#define IDC_BUTTON4                     1008
#define IDC_COLOR                       1010
#define IDC_RADIO1                      1010
#define IDC_RADIO2                      1011
#define IDC_GRID                        1013
#define IDC_LIST2                       1019
#define IDC_TREE1                       1020
#define IDC_STATIC1                     1022
#define IDC_RICHEDIT21                  1023
#define IDC_STATIC2                     1023
#define ID_WINDOW_CLOSE                 32772
#define ID_WINDOW_CLOSE_ALL             32773
#define ID_MAPLAYER_ADD                 32775
#define ID_MAPLAYER_REMOVE              32776
#define ID_MAPLAYER_UP                  32777
#define ID_MAPLAYER_DOWN                32778
#define ID_MAPLAYER_DUP                 32779
#define ID_MAPLAYER_MERGE               32780
#define ID_MAPEDIT_DRAW                 32786
#define ID_MAPEDIT_ERASE                32787
#define ID_MAPEDIT_FILL                 32788
#define ID_MAPEDIT_GRID                 32795
#define ID_MAPEDIT_PROP                 32796
#define ID_VIEW_ZOOMIN                  32801
#define ID_VIEW_ZOOMOUT                 32802
#define ID_VIEW_PROJVIEW                32809
#define ID_FILE_ADDNEWITEM              32810
#define ID_MAPTILESET_ADD               32815
#define ID_SPRITETILESET_INSERT         32816
#define ID_MAPTILESET_REMOVE            32819
#define ID_SPRITEEDIT_DRAW              32822
#define ID_SPRITEEDIT_ERASE             32823
#define ID_SPRITEPREVIEW_PLAY           32824
#define ID_SPRITEPREVIEW_PAUSE          32825
#define ID_SPRITEPREVIEW_STOP           32826
#define ID_SPRITEPREVIEW_PREVFRAME      32827
#define ID_SPRITEPREVIEW_NEXTFRAME      32828
#define ID_SPRITEEDIT_PROP              32829
#define ID_SPRITEPREVIEW_LOOP           32830
#define ID_LEVELEDIT_REMOVE             32832
#define ID_LEVELEDIT_SELITEM            32834
#define ID_LEVELEDIT_PROP               32835
#define ID_LEVELEDIT_DELITEM            32836
#define ID_LEVELEDIT_ADDSPRITE          32839
#define ID_LEVELEDIT_ADDBKGND           32840
#define ID_FILE_ADDNEWTEXTURE           32841
#define ID_FILE_ADDNEWMAP               32842
#define ID_FILE_ADDNEWSPRITE            32843
#define ID_FILE_ADDNEWOBJECT            32844
#define ID_FILE_ADDNEWLEVEL             32845
#define ID_LEVELEDIT_MOVEITEM           32846
#define ID_LEVELEDIT_MOVEUP             32847
#define ID_LEVELEDIT_MOVEDOWN           32848
#define ID_LEVELEDIT_TOPMOST            32849
#define ID_LEVELEDIT_BOTTOMMOST         32850
#define ID_PROJECT_RUNTHEGAME           32851
#define ID_PROJECT_CREATEEXECUTABLE     32852
#define ID_LEVELEDIT_LEVELUP            32855
#define ID_LEVELEDIT_LEVELDOWN          32856
#define ID_LEVELEDIT_GRID               32857
#define ID_SNAP_8                       32868
#define ID_SNAP_16                      32869
#define ID_SNAP_24                      32870
#define ID_SNAP_32                      32871
#define ID_SNAP_40                      32872
#define ID_SNAP_48                      32873
#define ID_SNAP_56                      32874
#define ID_SNAP_64                      32875
#define ID_SNAP_CUSTOMIZE               32876
#define ID_SPRITEEDIT_INSERT            32878
#define ID_LEVELEDIT_ADDTEXBG           32881
#define ID_LEVELEDIT_ADDMAPBG           32882
#define ID_FILE_ADDNEWSCRIPT            32883
#define ID_FILE_ADDNEWAUDIO             32885
#define ID_PROJECT_CREATEPACKAGE        32886
#define ID_PROJECT_PLAYFILE             32887
#define ID_VIEW_OUTPUTWINDOW            32888
#define ID_LEVELEDIT_ADDCOLBG           32891
#define ID_FILE_ADDNEWSTGE              32896
#define ID_VIEW_SHOWFPS                 32899
#define ID_FILE_ADDNEWDEPENDENCY        32901
#define ID_EDIT_GOTO                    32908
#define ID_HELP_GOODAPIREFERENCE        32910
#define ID_PROJECT_NEWSEARCHPATH        32912
#define ID_HELP_CHECKFORUPDATE          32913
#define ID_STGESCRIPT_SOURCE            32916
#define ID_STGESCRIPT_COMPILE           32919
#define ID_MAPEDIT_OPTION               32921
#define ID_STGESCRIPT_VIEW              32925
#define ID_LEVELEDIT_ALIGNLEFT          32926
#define ID_LEVELEDIT_ALIGNRIGHT         32927
#define ID_LEVELEDIT_ALIGNTOP           32928
#define ID_LEVELEDIT_ALIGNBOTTOM        32929
#define ID_VIEW_TEXTURE                 32930
#define ID_PROJECT_CREATEZIPPACKAGE     32932
#define ID_PROJECT_RUNTHISLEVEL         32933
#define ID_LEVELEDIT_ADDDUMMY           32936
#define ID_LEVELEDIT_LINE               32938
#define ID_0_CUSTOM                     32939
#define ID_LINE_CUSTOMIZE               32940
#define ID_LEVELEDIT_ADDLVLOBJ          32943

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        266
#define _APS_NEXT_COMMAND_VALUE         32945
#define _APS_NEXT_CONTROL_VALUE         1026
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
